language: csharp
solution: Nhom20.sln
install:
  - nuget restore Nhom20.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Nhom20.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./DemoTest/bin/Release/DemoTest.dll